### ISSUE TITLE
Node does not give access to Tree

### ISSUE THREAD

**Issue by Emmeral** [tree-sitter/java-tree-sitter#15]
Is there any reason the Node class does not give access to the Tree it belongs to?
The `Tree getTree()` method is package private. It could also be `public` such that the underlying tree can be accessed.
c.f. code [here](https://github.com/tree-sitter/java-tree-sitter/blob/master/src/main/java/io/github/treesitter/jtreesitter/Node.java#L38C1-L38C20)

**Comment by Emmeral** [comment]
When are you planning to publish the changes? They are not yet available on maven central.

**Comment by ObserverOfTime** [comment]
They are now.
