### ISSUE TITLE
Java API change suggestions

### ISSUE THREAD

**Issue by Marcono1234** [tree-sitter/java-tree-sitter#21]
Hello,
I noticed a few cases where the Java API might be a bit unconventional / inconsistent. Hopefully these suggestions are useful. Let me know what you think.

### `java.util.Enumeration` usage
`LookaheadIterator` implements `java.util.Enumeration`. While `Enumeration` is not deprecated, it is considered legacy API and [its documentation](https://docs.oracle.com/en/java/javase/22/docs/api/java.base/java/util/Enumeration.html) says:

> The functionality of this interface is duplicated by the [`Iterator`](https://docs.oracle.com/en/java/javase/22/docs/api/java.base/java/util/Iterator.html) interface. In addition, `Iterator` adds an optional remove operation, and has shorter method names. New implementations should consider using `Iterator` in preference to `Enumeration`.

Nowadays newly added JDK API uses `Iterator` and not `Enumeration` anymore, and I assume the same is true for other libraries. So having `LookaheadIterator` implement `Enumeration` might make it a bit more cumbersome to use.

### `extends Throwable`

`QueryError` `extends Throwable`. In Java the exception hierarchy is:
- `Throwable`
  - `Error`: "serious problems that a reasonable application should not try to catch" ([documentation](https://docs.oracle.com/en/java/javase/22/docs/api/java.base/java/lang/Error.html))
  - `Exception`: "conditions that a reasonable application might want to catch" ([documentation](https://docs.oracle.com/en/java/javase/22/docs/api/java.base/java/lang/Exception.html))
    - `RuntimeException`

So if a custom exception type directly `extends Throwable`, it is not really clear what that means: Is it a serious problem or not?
Additionally it makes exception handling more cumbersome: Users always explicitly have to catch `QueryError` (or declare `throws QueryError`) and cannot use `catch (Exception ...)`.

Based on how `QueryError` is used, I think it should `extends Exception`, maybe even `RuntimeException` (or specifically `IllegalArgumentException`). Because it just represents a problem that invalid data was provided to a method, similar to `Integer.parseInt("invalid")` or `Pattern.compile("invalid[")` (which throw `IllegalArgumentException` subclasses as well).

(For consistency maybe it should be named `QueryException` then, or `QueryCreationException`?)

### Mixed `@Nullable` and `Optional`
Parts of the API use `@Nullable` (e.g. `Node#getText`) whereas others use `Optional` (e.g. `Node#getParent`) as return type.

This feels a bit inconsistent. Is this intentional, or did this inconsistency happen by accident during development and was overlooked? Would it make sense to either consistently use `@Nullable` or `Optional`?

**Comment by ObserverOfTime** [comment]
> `java.util.Enumeration` usage

`LookaheadIterator` is immutable while `java.util.Iterator` is mutable.

> `extends Throwable`

We can have `QueryError` extend `Exception` or a subclass,
but its current name is consistent with the C API.

> Mixed `@Nullable` and `Optional`

`@Nullable` is used for strings while `Optional` is used for objects.

**Comment by Marcono1234** [comment]
> `LookaheadIterator` is immutable while `java.util.Iterator` is mutable.

It is kind of 'conditionally mutable'; if you don't override `Iterator#remove`, then it is immutable by default. And I think most users assume that `remove` throws `UnsupportedOperationException`, unless whatever created the iterator documented that it is supported.

But I can understand that this might be confusing for users that `LookaheadIterator` exposes an inherited `remove` method which is pointless. At least there is `Enumeration#asIterator`, so users can convert to an `Iterator` if desired.


> `@Nullable` is used for strings while `Optional` is used for objects.

Fair point, at least that is consistent. But you might call methods on the `String` as well so could run into a `NullPointerException` there too, or what was the reason to use `Optional` in the other cases?
I think the common Java IDEs nowadays recognize `@Nullable`, so maybe using `@Nullable` in all cases would be more convenient?

**Comment by ObserverOfTime** [comment]
> But you might call methods on the `String` as well so could run into a `NullPointerException` there too, or what was the reason to use `Optional` in the other cases?

`Optional` objects make it easier to chain methods, which to me felt unnecessary for strings.

**Comment by Marcono1234** [comment]
Thanks for the changes to `QueryError`. If you want feel free to close this issue, since you explained the rationale for the other API decisions.
